eureka:
  instance:
    hostname: bankatii-config-server.onrender.com
  client:
    service-url:
      defaultZone: https://bankatii-discovery-server.onrender.com/eureka

spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0
