eureka:
  instance:
    hostname: ms-config.onrender.com
  client:
    service-url:
      defaultZone: https://ms-discovery.onrender.com/eureka

spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0
