server:
  port: 8050
spring:
  data:
    mongodb:
      username: bankatidb
      password: bankatidb
      host: localhost
      port: 27018
      database: servicestiers
      authentication-database: admin

application:
  config:
    virtualCard-url: http://localhost:8222/api/v1/virtualcard
    wallet-url: http://localhost:8222/api/v1/wallet
    transactions-url: http://localhost:8222/api/v1/transactions
    users-url: http://localhost:8222/api/v1/users